### ISSUE TITLE
Encounter dangling reference with `OwnBox::<T>::deref/deref_mut`

### ISSUE THREAD

**Issue by shinmao** [aidancully/containerof#1]
### The source of unsoundness
https://github.com/aidancully/containerof/blob/58f7c164c1176a6478878ef8f512549aa1cc0949/src/lib.rs#L161-L165
Hi, we consider the implementation of `deref` and `deref_mut` are unsound because the memory at `self.get_address()` is unallocated. Therefore, if callers access the type after `transmute` will encounter a dangling reference.

### To reproduce the bug
```
use containerof::OwnBox;
use std::boxed::Box;

fn main() {
    let bx = Box::new(1u8);
    let ob = OwnBox::from_box(bx);
    println!("{:?}", *ob);
}
```
to run with miri,
```
error: Undefined Behavior: constructing invalid value: encountered a dangling reference (address 0x89140 is unallocated)
   --> /${HOME}/.cargo/registry/src/github.com-1ecc6299db9ec823/containerof-0.2.2/src/lib.rs:164:18
    |
164 |         unsafe { mem::transmute(self.get_address()) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value: encountered a dangling reference (address 0x89140 is unallocated)
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
```

**Comment by aidancully** [comment]
Thank you for your report, and I apologize for the delay addressing it. This should be fixed in v0.3.0 (just published).
